### PR TITLE
update list of Caliper repos and add descriptions

### PR DESCRIPTION
**Pull request by bracken**
The list was a little outdated, and incomplete.
This adds links to public versions of repos and
adds a description to help orient contributors.

### CODE REVIEW

**Comment by bracken** [comment]
So that you don't have to render the HTML from the diff in your head, check it out here: https://github.com/IMSGlobal/caliper-central/tree/update_repo_list

**Comment by ViktorHaag** [comment]
If we're calling this a markdown-formatted README, what's the need for inline HTML? It's way harder to read?

**Comment by bracken** [comment]
I just did an HTML table because I find Markdown tables super hard to create and to read in the plain text version because they take so much spacing maintenance. But I'm totally fine using them if that's our standard for doing it.

**Comment by ViktorHaag** [comment]
Ah, I see -- yeah -- I'm fine with the list of things as a list; if we want a table, I can see you might want to use HTML for maintenance rather than readability. 8)

**Comment by bracken** [comment]
Problem solved: https://jmalarcon.github.io/markdowntables/  haha

**Comment by ViktorHaag** [comment]
Niiiiiiice... 8)

**Comment by bracken** [comment]
changed them to markdown tables and added a couple more descriptions.

**Comment by ViktorHaag** [comment]
:shipit:

**Pull request merged**
